-- ONLINE_SALE
    -- ONLINE_SALE_ID, USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE
    -- PK : SALES_DATE, USER_ID, PRODUCT_ID
-- USER_ID(동일한 회원), PRODUCT_ID(동일한 상품)을 재구매한 데이터를 구하여
-- 재구매한 회원 ID, 재구매한 상품 ID 출력
SELECT USER_ID, PRODUCT_ID
FROM (
    SELECT USER_ID, PRODUCT_ID, COUNT(*) as SALE_CNT
    FROM ONLINE_SALE
    GROUP BY 1, 2
    HAVING SALE_CNT > 1
) a
ORDER BY 1, 2 DESC
